### ISSUE TITLE
Piwik doesn't play nice with MediaWiki 1.25's wfLoadExtension()

### ISSUE THREAD

**Issue by Ma-ve** [DaSchTour/piwik-mediawiki-extension#15]
As of MediaWiki 1.25, usage of require_once() is no longer needed, but a call to wfLoadExtension() is called. Code must be ported from Piwik.php to extension.json: auto tool provided by MediaWiki (core/maintenance/convertExtensionToRegistration) doesn't work sadly enough

**Comment by Seb35** [comment]
Solved with 0d099ad, 883a160, and 97a0cd5.

**Comment by Seb35** [comment]
This is now the branch 3.0, breaking compatibility with MediaWiki 1.24-, now published on Composer with the tag v3.0.0 and as a GitHub release 3.0.0.

As a courtesy for MediaWiki 1.24 and older, I also issued a tag v2.4.4 (and a GitHub release 2.4.4) with the state of the code just before this breaking commit. Well, in fact I issued a tag v2.4.3 but I forgot to update the version in Piwik.php and README, hence, instead of re-tagging (which would be bad) I created a new tag 2.4.4 with the versions updated in the files.
